music_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resource :session, only: [:destroy, :new, :create]
  resources :users, only: [:new, :show, :create]


  resources :bands do
  resources :albums, only: [:new]
  end

  resources :albums, only: [:show, :create, :edit, :update, :destroy] do
  resources :tracks, only: [:new]
  end

  resources :tracks, only: [:show, :create, :edit, :update, :destroy,]

  resources :notes, only: [:create, :destroy]
end

music_app/app/models/User.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, :password_digest, :session_token, presence: true, uniqueness: true

  after_initialize :ensure_session_token
  attr_reader :password

  def self.generate_session_token
    SecureRandom::urlsafe_base64
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil unless user && user.is_password?(password)
    user
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    self.update!(session_token: self.session_token)
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end



end

  #
  # validates :activation_token, :email, :session_token, uniqueness: true
  # validates :password, length: { minimum: 6, allow_nil: true }
  # validates :email,
  #           :password_digest,
  #           :session_token,
  #           :activation_token,
  #           presence: true
  #
  # attr_reader :password
  #
  # after_initialize :ensure_session_token
  # after_initialize :set_activation_token
  #
  # has_many :notes
  #
  # def self.find_by_credentials(email, password)
  #   user = User.find_by(email: email)
  #
  #   user && user.is_password?(password) ? user : nil
  # end
  #
  # def set_activation_token
  #   self.activation_token = generate_unique_activation_token
  # end


  # def reset_session_token!
  #   self.session_token = generate_unique_session_token
  #   self.save!
  #
  #   self.session_token
  # end
  #
  # def ensure_session_token
  #   self.session_token ||= generate_unique_session_token
  # end
  #
  # def generate_unique_session_token
  #   token = SecureRandom.urlsafe_base64(16)
  #
  #   ##
  #   # Just in case there is a session_token conflict, make sure
  #   # not to throw a validation error at the user!
  #   ##
  #   while self.class.exists?(session_token: token)
  #     token = SecureRandom.urlsafe_base64(16)
  #   end
  #
  #   token
  # end

  # ##
  # # This method is for the mailer!
  # ##
  # def generate_unique_activation_token
  #   token = SecureRandom.urlsafe_base64(16)
  #   while self.class.exists?(activation_token: token)
  #     token = SecureRandom.urlsafe_base64(16)
  #   end
  #   token
  # end
  #
  # def activate!
  #   self.update_attribute(:activated, true)
  # end

music_app/app/models/album.rb
class Album < ApplicationRecord

  belongs_to :band,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: 'Band'

  has_many :tracks
    primary_key: :id,
    foreign_key: :album_id,
    class_name: 'Track'

  validates :band, :name, :year, presence: true
  validates :live, inclusion: { in: [true, false] }
  validates :name, uniqueness: { scope: :band_id }
  validates :year, numericality: { minimum: 1900, maximum: 9000 }

  after_initialize :set_defaults

  def set_defaults
    self.live ||= false
  end
end

music_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

music_app/app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :albums,
    primary_key: :id,
    foreign_key: :band_id,
    class_name: 'Album'

end

music_app/app/models/track.rb
class Track < ApplicationRecord
  # validates :lyrics, :name, :ord, presence: true
  # validates :bonus, inclusion: { in: [true, false] }
  # validates :ord, uniqueness: { scope: :album_id }

  belongs_to :album,
    primary_key: :id,
    foreign_key: :album_id,
    class_name: 'Album'

  has_one :band,
    through: :album,
    source: :band

  # has_many :notes,
  #   primary_key: :id,
  #   foreign_key: :

  after_initialize :set_defaults

  def set_defaults
    self.bonus ||= false
  end
end

music_app/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_user!

  def show
    @album = Album.find(params[:id])
    render :show
  end

  def new
    @band = Band.find(params[:band_id])
    @album = Album.new(band_id: params[:band_id])
    render :new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to album_url(@album)
    else
      @band = @album.band
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
    render :edit
  end

  def update
    @album = Album.find(params[:id])

    if @album.update(album_params)
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to band_url(@album.band_id)
  end

  private

  def album_params
    params.require(:album).permit(:band_id, :live, :name, :year)
  end
end

music_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def ensure_logged_in
    redirect_to new_session_url unless logged_in?
  end

  def log_in_user!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logged_in?
    !!current_user
  end

end

music_app/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  # before_action :require_user!

  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find(params[:id])
    render :edit
  end

  def update
    @band = Band.find(params[:id])
    if @band.update(band_params)
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    @band = Band.find(params[:id])
    @band.destroy
    redirect_to bands_url
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

music_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:email],
      params[:user][:password]
    )

    if user.nil?
      flash.now[:errors] = ["Invalid email or password"]
      render :new
    # elsif !user.activated?
    #   flash.now[:errors] = ['Activate your account. Check your inbox!']
    #   render :new
    else
      log_in_user!(user)
      redirect_to root_url
    end
  end

  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end


end

music_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in_user!(@user)
      redirect_to new_user_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

music_app/app/helpers/application_helper.rb
module ApplicationHelper
end

music_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

music_app/app/helpers/users_helper.rb
module UsersHelper
end

music_app/app/views/bands/edit.html.erb
<!DOCTYPE html>
<html>
<h1 class='page-header'>Edit <%= @band.name %></h1>

<%= render "form", band: @band %>
<html>

music_app/app/views/bands/form.html.erb
<!-- <!DOCTYPE html>
<html> -->

<% action_url = band.persisted? ? band_url(band) : bands_url %>
<% http_method = band.persisted? ? "PATCH" : "POST" %>

<form class='form' action="<%= action_url %>" method="POST">
  <input type="hidden" name="_method" value="<%= http_method %>">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <p>
    <label for='band-name'>Name</label>
    <input id='band-name' type="text" name="band[name]" value="<%= band.name %>">
  </p>

  <input type="submit">
</form>
<!-- </html> -->

music_app/app/views/bands/index.html.erb
<!DOCTYPE html>
<html>
<h1 class='page-header'>Bands</h1>

<ul class='main-list'>
  <% @bands.each do |band| %>
    <li><a href="<%= band_url(band) %>"><p><%= band.name %></p></a></li>
  <% end %>
</ul>

<h4 class='sub-header'>Links</h4>
<ul class='page-links'>
  <li><a class='button' href="<%= new_band_url %>" >New band</a></li>
</ul>
</html>

<style >
  li { border-width: 30px; background-color: #eeffba; color: white; }
  h1 {font-family: monospace;}
  h4 { background-color: purple; font-size: 60px; font-style: italic; font-family: monospace; }
</style>
<html>

music_app/app/views/bands/new.html.erb
<!-- <!DOCTYPE html>
<html> -->
<h1 class='page-header'>New Band!</h1>
<%= render "form", band: @band %>

<!-- </html> -->

music_app/app/views/bands/show.html.erb
<!DOCTYPE html>
<html>
<h1 class='page-header'><%= @band.name %></h1>

<h4 class='sub-header'>Albums</h4>

<% if @band.albums.length > 0 %>
  <ul class='main-list'>
  <% @band.albums.each do |album| %>
    <li><a href="<%= album_url(album) %>"><p><%= album.name %></p></a></li>
  <% end %>
  </ul>
<% else %>
  <p>no albums yet :(()) </p>
<% end %>

<h4 class='sub-header'>Links</h4>
<ul class='page-links'>
  <li><a class='button' href="<%= new_band_album_url(@band) %>">New album</a></li>
  <li><a class='button' href="<%= edit_band_url(@band) %>">Edit Band</a></li>
  <li>
    <form action="<%= band_url(@band) %>" method="POST">
      <input type="hidden" name="_method" value="DELETE">
      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
      <input type="submit" value="Destroy Band">
    </form>
  </li>
  <li><a class='button' href="<%= bands_url %>">All bands</a></li>
</ul>
</html>

music_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>

<style>
  h1 {
    color:red;
    background-color: #61f441;
    text-align: center;
    font-style: oblique;
    border-radius: 100px;
    font-size: 100px;
  }
</style>

<div style=”width: 25%; height: 50px; overflow: auto; scrollbar-face-color: #CE7E00; scrollbar-shadow-color: #FFFFFF; br /scrollbar-highlight-color: #6F4709; scrollbar-3dlight-color:#11111; scrollbar-darkshadow-color: #6F4709; br /scrollbar-track-color: #FFE8C1; scrollbar-arrow-color: #6F4709;”>This is real </div>

  <body>
    <div class='main-content'>
      <h1 class='main-logo'>Music App</h1>
      <% if current_user %>
        <nav>
          <a class='button' href="<%= bands_url %>">Take me Home</a>

          <div class='user-detail'>
            <p>Logged in as: <%= current_user.email %></p>
          <form action=<%= session_url %> method='post'>
            <input
              type="hidden"
              name="_method"
              value="delete">
            <input
              type="hidden"
              name="authenticity_token"
              value="<%= form_authenticity_token %>">
            <input
              type="submit" value="Sign Out">
          </form>
          </div>
        </nav>
      <% end %>

      <% if flash[:notice] %>
        <p><%= flash[:notice] %></p>
      <% end %>

      <% if flash[:errors] %>
        <p><%= flash[:errors].join(", ") %></p>
      <% end %>
    <%= yield %>
    </div>
  </body>
</html>

music_app/app/views/users/new.html.erb
<a class='button' href=<%= new_session_url %> >Sign In</a>
<br>
<h3 class='page-header'>New User</h3>
 <style>
   h3 {color:#f47f41; background-color: #4195f4; background-position: center; font-size: 40px; text-align: center;}
   form {text-align: center; background-color: #4195f4; border-radius: 20px; border-color: #fff6dd; border-width: 40px;}
   a {text-align: center;}
 </style>
<form class='form' action="<%= users_url %>" method="post">
  <br>
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for='new-user-email'>Email</label>
  <input id='new-user-email' type="text" name="user[email]">
  <br>
  <br>
  <label for='new-user-password'>Password</label>
  <input id='new-user-password' type="password" name="user[password]">
  <br>
  <br>
  <input type="submit" value="Submit">
  <br>
  <br>
</form>

music_app/app/views/users/show.html.erb
<h1 class='page-header'>User Profile</h1>
<p>
  Email: <%= current_user.email %>
</p>